on:
  push:
    branches:
      - master

name: Deploy to kubernetes
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    - name: Setup Minikube
      uses: manusa/actions-setup-minikube@v1.0.2
      with:
        minikube version: 'v1.9.2'
        kubernetes version: 'v1.18.2'
        github token: ${{ secrets.GITHUB_TOKEN }}
    - name: Interact with the cluster
      run: kubectl get nodes
