on:
  push:
    branches:
      - master

name: Deploy to kubernetes
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!
    - name: apt install minikube
      run: apt install minikube

