on:
  push:
    branches:
      - master

name: Deploy to kubernetes
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!
    - name: apt install minikube
      run: curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 
      
    - name: minikube
      run: chmod +x minikube && sudo cp minikube /usr/local/bin && rm minikube
    
    - name: version
      run: minikube version
    
    - name: start
      run: sudo minikube start

