on:
  push:
    branches:
      - master

name: Deploy to kubernetes
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!
    
    - name: updating
      run: sudo apt-get update && sudo apt-get install -y apt-transport-https
    
    - name: box
      run: sudo apt-get install -y virtualbox virtualbox-ext-pack
    
    - name: data
      run: curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add - && sudo touch /etc/apt/sources.list.d/kubernetes.list && echo "deb http://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee -a /etc/apt/sources.list.d/kubernetes.list && sudo apt-get update && sudo apt-get update && sudo apt-get install -y kubectl

    - name: minikube
      run: curl -Lo minikube https://storage.googleapis.com/minikube/releases/v0.28.2/minikube-linux-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/


