on:
  push:
    branches:
      - master

name: Deploy to kubernetes
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      if: ${{whoami=runner}}

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world! && whoami && id
    
    - name: updating
      run: apt -y update && apt install -y apt-transport-https

    - name: data
      run: curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 && chmod +x minikube

    - name: minikube
      run: cp minikube /usr/local/bin && rm minikube
    
    - name: start
      run: minikube start


